jobs:
  include:
    - stage: test
      language: go
      go: 1.9.x
      install:
        - go get -u github.com/gordonklaus/ineffassign
      script:
        - make test
    - stage: test
      language: go
      go: 1.10.x
      install:
        - go get -u github.com/gordonklaus/ineffassign
      script:
        - make test
    - stage: test
      language: go
      go: 1.11.x
      install:
        - go get -u github.com/gordonklaus/ineffassign
      script:
        - make test
    - stage: test
      language: go
      go: 1.10.x
      script:
        - go build -o /dev/null ./examples/getcoincreators
        - go build -o /dev/null ./examples/getcoins
        - go build -o /dev/null ./examples/getmultisigaddresses
        - go build -o /dev/null ./examples/getstats
    - stage: test
      language: go
      go: 1.11.x
      script:
        - go build -o /dev/null ./examples/getcoincreators
        - go build -o /dev/null ./examples/getcoins
        - go build -o /dev/null ./examples/getmultisigaddresses
        - go build -o /dev/null ./examples/getstats
